version: '3.7'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    volumes:
      - ../kibana:/usr/share/kibana/config
    environment:
      - "LOGGING_QUIET=true"
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.0
    ports:
      - 5044:5044
    volumes:
      - ../logstash/pipeline:/usr/share/logstash/pipeline/
    environment:
      LOG_LEVEL: error
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    environment:
      - cluster.name=elk
      - bootstrap.memory_lock=true
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

volumes:
  es_data:
    driver: local