version: '3.7'

services:

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.0
    volumes:
      - ../logstash/test:/usr/share/logstash/pipeline/
      - ../logstash/data:/usr/tmp
    environment:
      LOG_LEVEL: error
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    environment:
      - cluster.name=test
      - bootstrap.memory_lock=true
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_test:/usr/share/elasticsearch/data

volumes:
  es_test:
    driver: local

